--inserts de la tabla veterinaria
INSERT INTO VETERINARIA (ID_VETERINARIA, TAMANO, SERVICIO) VALUES (101, 'G', 'Vacunacion');
INSERT INTO VETERINARIA (ID_VETERINARIA, TAMANO, SERVICIO) VALUES (102, 'P', 'Estética');
INSERT INTO VETERINARIA (ID_VETERINARIA, TAMANO, SERVICIO) VALUES (103, 'M', 'Consulta G.');
INSERT INTO VETERINARIA (ID_VETERINARIA, TAMANO, SERVICIO) VALUES (104, 'M', 'Emergencia');

--inserts de tabla ubicacion
INSERT INTO UBICACION (ID_UBICACION, ID_VETERINARIA, CIUDAD, ESTADO) VALUES (80, 101, 'L.A', 'California');
INSERT INTO UBICACION (ID_UBICACION, ID_VETERINARIA, CIUDAD, ESTADO) VALUES (81, 102, 'Chicago', 'Illinois');
INSERT INTO UBICACION (ID_UBICACION, ID_VETERINARIA, CIUDAD, ESTADO) VALUES (82, 103, 'Houston', 'Texas');
INSERT INTO UBICACION (ID_UBICACION, ID_VETERINARIA, CIUDAD, ESTADO) VALUES (83, 104, 'New York', 'New York');

--inserts de tabla dueño
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2545, 'Hazel', 'Briceño', 'Masis', '123 Main ST, Anytown, CA 90210', '(310) 555-1234');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2689, 'Valeska', 'Muedano', 'Porras', '456 Elm ST, Springfield, IL 62701', '(217) 555-5678');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2548, 'Laura', 'Masis', 'Jiron', '789 Oak St, Smalltown, TX 75001', '(214) 555-9012');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2310, 'Paula', 'Soto', 'Marin', '321 Maple Ave, Cityville, NY 10001', '(212) 555-3456');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2784, 'Mauricio', 'Mendez', 'Gomez', '567 Pine St, Lakeside, FL 33000', '(305) 555-7890');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2851, 'Judy', 'Quesada', 'Solis', '890 Cedar St, Mountainview, WA 98001', '(206) 555-2345');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2378, 'Freddy', 'Urbina', 'Hurtado', '234 Birch St, Riverside, OH 43004', '(614) 555-6789');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2145, 'Cristian', 'Camarena', 'Roca', '876 Walnut St, Hillcrest, PA 19001', '(215) 555-4321');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2487, 'Rosa', 'Solis', 'Quesada', '543 Ash St, Beachside, NC 27501', '(919) 555-8765');
INSERT INTO DUENO (ID_DUENO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO)
VALUES (2912, 'Alexander', 'Hamilton', 'Smith', '210 Chestnut St, Lakeshore, MI 49001', '(313) 555-2109');

--inserts de tabla mascota
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (1, 'PERRO', 2912, 'LUNA', 'LABRADOR');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (2, 'GATO', 2487, 'MAX', 'BIRMANO');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (3, 'PERRO', 2145, 'BELLA', 'PASTOR ALEMAN');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (4, 'SERPIENTE', 2378, 'ROCKY', 'PÍTON');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (5, 'CONEJO', 2851, 'COCO', 'MINI REX');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (6, 'PERRO', 2784, 'LOLA', 'GOLDEN RETRIEVER');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (7, 'GATO', 2310, 'BUDDY', 'MANX');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (8, 'HAMSTER', 2548, 'DAISY', 'ROBOROVSKI');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (9, 'PERRO', 2689, 'CHARLIE', 'POODLE');
INSERT INTO MASCOTA (ID_MASCOTA, TIPO_MASCOTA, ID_DUENO, NOMBRE_MASCOTA, RAZA) VALUES (0, 'COBAYA', 2545, 'LUCY', 'PERUANA');

--inserts tabla detalle mascota
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (0, 1, '2 AÑOS', '36KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (1, 2, '4 AÑOS', '3.5KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (2, 3, '6 AÑOS', '30KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (3, 4, '8 MESES', '1KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (4, 5, '2 MESES', '0.5KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (5, 6, '9 AÑOS', '34KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (6, 7, '5 AÑOS', '4KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (7, 8, '1 MES', '25G');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (8, 9, '5 AÑOS', '5KG');
INSERT INTO DETALLE_MASCOTA (ID_DETALLE_MASCOTA, ID_MASCOTA, EDAD, PESO)
VALUES (9, 0, '6 AÑOS', '0.7KG');

--Inserts de tabla especialista
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10001, 'MEDICINA PREVENTIVA', 'Juan', 'Peréz', 'Chacon', '(123) 456-7890', 101);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10002, 'CIRUGÍA VETERINARIA', 'María', 'García', 'Mendez', '(234) 567-8901', 101);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10003, 'CONSULTA CLÍNICA', 'David', 'Rodríguez', 'Solis', '(345) 678-9012', 101);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10004, 'MEDICINA PREVENTIVA', 'Ana', 'Martínez', 'Porras', '(456) 789-0123', 102);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10005, 'CIRUGÍA VETERINARIA', 'Carlos', 'López', 'Perez', '(567) 890-1234', 102);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10006, 'MEDICINA PREVENTIVA', 'Laura', 'Gonzáles', 'Alfaro', '(678) 901-2345', 103);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10007, 'CIRUGÍA VETERINARIA', 'Alejandro', 'Díaz', 'Masis', '(789) 012-3456', 103);
INSERT INTO ESPECIALISTA (ID_ESPECIALISTA, ESPECIALIDAD, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, ID_VETERINARIA)
VALUES (10008, 'CONSULTA CLÍNICA', 'Andrea', 'Fernandez', 'Lopez', '(890) 123-4567', 104);

--inserts tabla detalle especialista
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (50, 10001, 60000, TO_DATE('2023-05-15', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (51, 10002, 100000, TO_DATE('2022-09-20', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (52, 10003, 80000, TO_DATE('2024-01-10', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (53, 10004, 90000, TO_DATE('2023-11-30', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (54, 10005, 85000, TO_DATE('2022-07-05', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (55, 10006, 65000, TO_DATE('2023-03-10', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (56, 10007, 72000, TO_DATE('2022-12-15', 'YYYY-MM-DD'));
INSERT INTO DETALLE_ESPECIALISTA (ID_DETALLE_ESPECIALISTA, ID_ESPECIALISTA, SALARIO, FECHA_CONTRATACION)
VALUES (57, 10008, 68000, TO_DATE('2024-02-20', 'YYYY-MM-DD'));

--inserts de la tabla medicamento
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1802, 'Amoxicilina', TO_DATE('2024-08-15', 'YYYY-MM-DD'), 10);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1054, 'Prednisona', TO_DATE('2024-10-22', 'YYYY-MM-DD'), 15);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1035, 'Metronidazol', TO_DATE('2024-09-30', 'YYYY-MM-DD'), 12);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1678, 'Enalapril', TO_DATE('2024-11-10', 'YYYY-MM-DD'), 20);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1158, 'Ibuprofeno', TO_DATE('2024-07-25', 'YYYY-MM-DD'), 8);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1562, 'Omeprazol', TO_DATE('2024-09-05', 'YYYY-MM-DD'), 18);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1105, 'Tramadol', TO_DATE('2024-08-30', 'YYYY-MM-DD'), 25);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1672, 'Ciprofloxacino', TO_DATE('2024-10-15', 'YYYY-MM-DD'), 14);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1345, 'Dipirona', TO_DATE('2024-07-31', 'YYYY-MM-DD'), 6);
INSERT INTO MEDICAMENTO (ID_MEDICAMENTO, NOMBRE, FECHA_CADUCIDAD, PRECIO)
VALUES (1045, 'Fluoxetina', TO_DATE('2024-09-18', 'YYYY-MM-DD'), 22);

--inserts de tabla detalle de medicamento
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (40, 1802, 'Antibiótico', '8:00 am - 20:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (41, 1054, 'Antiinflamatorio', '9:00pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (42, 1035, 'Antibiótico', '8:00 am - 14:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (43, 1678, 'Medicamento para la presión arterial', '8:00pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (44, 1158, 'Analgésico', '12:00 md - 18:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (45, 1562, 'Antiácido', '9:00 am - 21:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (46, 1105, 'Analgésico', '8:00 am - 16:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (47, 1672, 'Antibiótico', '8:00 am - 20:00 pm');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (48, 1345, 'Analgésico', '8:00 am - 12:00 md');
INSERT INTO DETALLE_MEDICAMENTO (ID_DETALLE_MEDICAMENTO, ID_MEDICAMENTO, TIPO_MEDICAMENTO, HORARIO_DOSIS)
VALUES (49, 1045, 'Antidepresivo', '10:00am');

--inserts de tabla cita
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (300, 0, 2689, 102, 10008, 'Baño y corte de pelo', TO_DATE('24/03/2024', 'DD/MM/YYYY'), 'Presente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (301, 9, 2545, 101, 10004, 'Vacunacion', TO_DATE('25/06/2024', 'DD/MM/YYYY'), 'Ausente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (302, 6, 2310, 104, 10002, 'Operación', TO_DATE('30/10/2024', 'DD/MM/YYYY'), 'Pendiente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (303, 7, 2548, 104, 10007, 'Castracion', TO_DATE('25/11/2024', 'DD/MM/YYYY'), 'Pendiente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (304, 8, 2784, 103, 10003, 'Control de mes', TO_DATE('03/02/2024', 'DD/MM/YYYY'), 'Presente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (305, 5, 2378, 103, 10001, 'Receta de medicamentos', TO_DATE('18/05/2024', 'DD/MM/YYYY'), 'Pendiente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (306, 1, 2851, 102, 10003, 'Corte de uñas', TO_DATE('09/03/2024', 'DD/MM/YYYY'), 'Presente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (307, 3, 2487, 102, 10008, 'Estetica completa', TO_DATE('10/04/2024', 'DD/MM/YYYY'), 'Ausente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (308, 2, 2145, 103, 10006, 'Control de sarna', TO_DATE('30/05/2024', 'DD/MM/YYYY'), 'Ausente');
INSERT INTO CITA (ID_CITA, ID_MASCOTA, ID_DUENO, ID_VETERINARIA, ID_ESPECIALISTA, RAZON_CITA, FECHA_CITA, ESTADO)
VALUES (309, 4, 2912, 103, 10004, 'Inyeccion de insulina', TO_DATE('30/06/2024', 'DD/MM/YYYY'), 'Pendiente');

--inserts de vacuna
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1568, 'Vacuna para diabetes', 'Vacuna parA la diabetes,enfermedad que afecta a los perros.', TO_DATE('30/11/2024', 'DD/MM/YYYY'), 30);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1242, 'Rabia', 'Prevención contra la rabia, una enfermedad viral mortal transmitida a través de la saliva de animales infectados.', TO_DATE('15/10/2024', 'DD/MM/YYYY'), 35);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1233, 'Moquillo', 'Vacuna para prevenir el moquillo canino, una enfermedad viral altamente contagiosa.', TO_DATE('22/09/2024', 'DD/MM/YYYY'), 28);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1634, 'Leptospirosis', 'Prevención contra la leptospirosis, una enfermedad bacteriana transmitida por la orina de animales infectados.', TO_DATE('28/08/2024', 'DD/MM/YYYY'), 32);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1895, 'Bordetella', 'Vacuna para prevenir la tos de las perreras, una enfermedad respiratoria altamente contagiosa.', TO_DATE('10/10/2024', 'DD/MM/YYYY'), 25);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1056, 'Coronavirus canino', 'Protege contra el coronavirus canino, que puede causar gastroenteritis en perros.', TO_DATE('15/09/2024', 'DD/MM/YYYY'), 28);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1737, 'Lyme', 'Prevención contra la enfermedad de Lyme, transmitida por garrapatas infectadas.', TO_DATE('05/11/2024', 'DD/MM/YYYY'), 40);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1248, 'Parvovirus', 'Vacuna para prevenir el parvovirus canino, una enfermedad viral altamente contagiosa.', TO_DATE('20/07/2024', 'DD/MM/YYYY'), 30);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1359, 'Tos de las perreras', 'Vacuna para prevenir la tos de las perreras, una enfermedad respiratoria que afecta a los perros.', TO_DATE('10/08/2024', 'DD/MM/YYYY'), 25);
INSERT INTO VACUNA (ID_VACUNA, NOMBRE, DESCRIPCION, FECHA_CADUCIDAD, PRECIO)
VALUES (1890, 'Hepatitis canina', 'Protege contra la hepatitis canina, una enfermedad viral que afecta el hígado de los perros.', TO_DATE('30/09/2024', 'DD/MM/YYYY'), 35);

--inserts de enfermedad
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1126, 'Parvovirus', 'El parvovirus canino es una enfermedad altamente contagiosa que afecta principalmente a cachorros.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1622, 'Dermatitis', 'La dermatitis en mascotas puede ser causada por alergias, parásitos o infecciones bacterianas.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1623, 'Otitis', 'La otitis es una inflamación del oído que puede causar molestias y dolor en las mascotas.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1964, 'Leptospirosis', 'La leptospirosis es una enfermedad bacteriana transmitida por la orina de animales infectados.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1035, 'Gingivitis', 'La gingivitis es una inflamación de las encías que puede causar mal aliento y molestias al comer.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1056, 'Moquillo', 'El moquillo es una enfermedad viral altamente contagiosa que afecta a los perros, especialmente cachorros.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1347, 'Conjunctivitis', 'La conjunctivitis en mascotas se caracteriza por la inflamación de la membrana que recubre el ojo.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1068, 'Sarna', 'La sarna es una enfermedad de la piel causada por ácaros que pueden provocar picazón y pérdida de pelo.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1569, 'Bronquitis', 'La bronquitis en mascotas puede ser causada por infecciones virales o bacterianas, o por alergias.');
INSERT INTO ENFERMEDAD (ID_ENFERMEDAD, NOMBRE, DESCRIPCION)
VALUES (1170, 'Diabetes', 'La diabetes en mascotas requiere manejo cuidadoso de la dieta y, en algunos casos, inyecciones de insulina.');

--inserts de factura
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4569, TO_DATE('15/02/2024', 'DD/MM/YYYY'), 'BAÑO Y CORTE', 2689, 102, 20);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4875, TO_DATE('01/03/2024', 'DD/MM/YYYY'), 'CONTROL DE MES', 2545, 101, 40);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4102, TO_DATE('26/01/2024', 'DD/MM/YYYY'), 'CORTE DE UÑAS', 2310, 104, 10);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4302, TO_DATE('30/01/2024', 'DD/MM/YYYY'), 'VACUNACION', 2548, 104, 30);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4789, TO_DATE('25/02/2024', 'DD/MM/YYYY'), 'VACUNACION POR RABIA', 2784, 103, 35);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4236, TO_DATE('29/02/2024', 'DD/MM/YYYY'), 'CONTROL DE MOQUILLO', 2378, 103, 28);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4720, TO_DATE('15/03/2024', 'DD/MM/YYYY'), 'INYECCION DE INSULINA', 2851, 102, 30);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4561, TO_DATE('02/03/2024', 'DD/MM/YYYY'), 'CORTE DE UÑAS', 2487, 102, 10);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4254, TO_DATE('04/03/2024', 'DD/MM/YYYY'), 'CASTRACION', 2145, 103, 50);
INSERT INTO FACTURA (ID_FACTURA, FECHA_FACTURA, DESCRIPCION, ID_DUENO, ID_VETERINARIA, SUB_TOTAL)
VALUES (4954, TO_DATE('31/01/2024', 'DD/MM/YYYY'), 'VACUNA POR LYME', 2912, 103, 40);

--inserts de expediente
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (400, 300, 0, 2689, 10008);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (401, 301, 9, 2545, 10004);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (402, 302, 6, 2310, 10002);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (403, 303, 7, 2548, 10007);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (404, 304, 8, 2784, 10003);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (405, 305, 5, 2378, 10001);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (406, 306, 1, 2851, 10003);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (407, 307, 3, 2487, 10008);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (408, 308, 2, 2145, 10006);
INSERT INTO EXPEDIENTE (ID_EXPEDIENTE, ID_CITA, ID_MASCOTA, ID_DUENO, ID_ESPECIALISTA)
VALUES (409, 309, 4, 2912, 10004);

--inserts de expediente de vacuna
INSERT INTO EXPEDIENTE_VACUNA (ID_EXP_VACUNA, ID_EXPEDIENTE, ID_VACUNA)
VALUES (20, 404, 1248);
INSERT INTO EXPEDIENTE_VACUNA (ID_EXP_VACUNA, ID_EXPEDIENTE, ID_VACUNA)
VALUES (21, 405, 1233);
INSERT INTO EXPEDIENTE_VACUNA (ID_EXP_VACUNA, ID_EXPEDIENTE, ID_VACUNA)
VALUES (22, 408, 1242);
INSERT INTO EXPEDIENTE_VACUNA (ID_EXP_VACUNA, ID_EXPEDIENTE, ID_VACUNA)
VALUES (23, 409, 1568);

--inserts de expediente de enfermedad
INSERT INTO EXPEDIENTE_ENFERMEDAD (ID_EXP_ENFERMEDAD, ID_EXPEDIENTE, ID_ENFERMEDAD)
VALUES (1, 404, 1126);
INSERT INTO EXPEDIENTE_ENFERMEDAD (ID_EXP_ENFERMEDAD, ID_EXPEDIENTE, ID_ENFERMEDAD)
VALUES (2, 405, 1056);
INSERT INTO EXPEDIENTE_ENFERMEDAD (ID_EXP_ENFERMEDAD, ID_EXPEDIENTE, ID_ENFERMEDAD)
VALUES (3, 408, 1622);
INSERT INTO EXPEDIENTE_ENFERMEDAD (ID_EXP_ENFERMEDAD, ID_EXPEDIENTE, ID_ENFERMEDAD)
VALUES (4, 409, 1170);

--inserts de expediente de medicamentos
INSERT INTO EXPEDIENTE_MEDICAMENTO (ID_EXP_MEDICAMENTO, ID_EXPEDIENTE, ID_MEDICAMENTO)
VALUES (10, 404, 1672);
INSERT INTO EXPEDIENTE_MEDICAMENTO (ID_EXP_MEDICAMENTO, ID_EXPEDIENTE, ID_MEDICAMENTO)
VALUES (11, 405, 1035);
INSERT INTO EXPEDIENTE_MEDICAMENTO (ID_EXP_MEDICAMENTO, ID_EXPEDIENTE, ID_MEDICAMENTO)
VALUES (12, 408, 1802);
INSERT INTO EXPEDIENTE_MEDICAMENTO (ID_EXP_MEDICAMENTO, ID_EXPEDIENTE, ID_MEDICAMENTO)
VALUES (13, 409, 1105);